Dockerfile  docker-compose.yml	docker-compose.yml-org	docker.env
root@Mysql-rc:/opt/mysql-rc# cat Dockerfile 
FROM mariadb:10.1-hc
RUN apt-get update && apt-get -y install percona-xtrabackup openssh-client
